# ansible-playbook-pssid-daemon contains requirements.yml which has the source of three dependent roles
# test command: ansible-playbook -i "198.111.226.184," test-playbook.yml --become   --become-method su   --become-user root   --ask-become-pass

---

# clone ansible-playbook-pssid-daemon repo
# status -- checked
- name: Clone ansible-playbook-pssid-daemon repository
  git:
    repo: https://github.com/UMNET-perfSONAR/ansible-playbook-pssid-daemon.git
    dest: /usr/lib/pssid/playbooks/ansible-playbook-pssid-daemon
    version: main  # replace with branch name in dev mode  <lu-implement-playbook-pssid-daemon>

# create role directory
# status -- checked
- name: Ensure roles directory exists
  file:
    path: /usr/lib/pssid/playbooks/ansible-playbook-pssid-daemon/roles
    state: directory
    mode: '0755'

# status -- unchecked (prompt authentication on commandline)
- name: Install roles using ansible-galaxy
  command:
    cmd: ansible-galaxy install -f -r requirements.yml
  args:
    chdir: /usr/lib/pssid/playbooks/ansible-playbook-pssid-daemon/

