# install ansible on GUI server
# STATUS - checked

---
# You may want to use apt-get rather than apt in older versions. 
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present

# Note only newer distributions have a -u or --update flag
- name: Add Ansible PPA
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
    update_cache: yes

# OB: like github, may fail on first run
- name: Install Ansible
  apt:
    name: ansible
    state: present
